# -*- coding: utf-8 -*-
"""CARE ME

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xlpAKTuIUVGkPJh72JCkZgP9VIT0U1-s
"""

import pandas as pd

# Load the data from the CSV file
try:
    df = pd.read_csv('/content/1.csv',encoding='ISO-8859-1')
    print("Data loaded successfully.")
except FileNotFoundError:
    print("File not found. Please check the file path and try again.")
    exit()

# Function to display data based on product NDC
def display_data(product_ndc):
    # Filter the data
    product_data = df[df['PRODUCTNDC'] == product_ndc]

    # Check if product NDC exists in the data
    if product_data.empty:
        print("The entered PRODUCTNDC was not found in the data.")
        return None

    # Display the other three columns
    return product_data[['PRODUCTID', 'ROUTENAME', 'ACTIVE_INGRED_UNIT']]

# Load user data if it exists
try:
    user_data = pd.read_csv('/content/drive/MyDrive/files/p.csv')
except FileNotFoundError:
    user_data = pd.DataFrame(columns=['Name', 'Phone Number', 'Age', 'PRODUCTNDC'])

# Get user details
name = input("Enter your name: ")

phone_number = input("Enter your phone number: ")
while not phone_number.isdigit() or len(phone_number) != 10:
    print("Invalid phone number. Please enter exactly 10 digits.")
    phone_number = input("Enter your phone number: ")

# Convert 'Phone Number' column to string
user_data['Phone Number'] = user_data['Phone Number'].astype(str)

# Check if user has used the application before
if phone_number in user_data['Phone Number'].values:
    print("Good to see you again!")

age = input("Enter your age: ")
while not age.isdigit() or int(age) <= 0:
    print("Invalid age. Please enter a positive integer.")
    age = input("Enter your age: ")

# Get product NDC from user
product_ndc = input("Enter the PRODUCTNDC: ")

# Display the data
print(display_data(product_ndc))

# Store user details and product NDC
new_user_data = pd.DataFrame({'Name': [name], 'Phone Number': [phone_number], 'Age': [age], 'PRODUCTNDC': [product_ndc]})
user_data = pd.concat([user_data, new_user_data], ignore_index=True)
user_data.to_csv('/content/drive/MyDrive/files/p.csv', index=False)

